sudo: false
language: python
python: "3.4"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py27
#    - TESTENV=py27-xdist
    - TESTENV=py27-pytest-latest
    - TESTENV=py34
#    - TESTENV=coveralls
before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://mark.stridespace.com

install:
  - pip install tox

script: 
  - tox -e $TESTENV --recreate
  - testspace [$TESTENV].tox/$TESTENV/log/junit*.xml

  #- testspace [$TESTENV].tox/$TESTENV/log/junit*.xml{tests}

#branches:
#  except:
#    - /^\d/
#notifications:
#  email:
#  - bubenkoff@gmail.com
#  - oleg.pidsadnyi@gmail.com
